
-- Add missing fields to visites table based on Safari software screenshots
ALTER TABLE public.visites
  ADD COLUMN IF NOT EXISTS code text,
  ADD COLUMN IF NOT EXISTS call_date date,
  ADD COLUMN IF NOT EXISTS zone text,
  ADD COLUMN IF NOT EXISTS scheduled_time time,
  ADD COLUMN IF NOT EXISTS duration interval DEFAULT '01:00:00',
  ADD COLUMN IF NOT EXISTS visit_type text,
  ADD COLUMN IF NOT EXISTS origin text,
  ADD COLUMN IF NOT EXISTS advisor text,
  ADD COLUMN IF NOT EXISTS coordinator text,
  ADD COLUMN IF NOT EXISTS comment text,
  ADD COLUMN IF NOT EXISTS instructions text,
  ADD COLUMN IF NOT EXISTS on_hold boolean DEFAULT false,
  -- Origin address fields
  ADD COLUMN IF NOT EXISTS origin_reference text,
  ADD COLUMN IF NOT EXISTS origin_name text,
  ADD COLUMN IF NOT EXISTS origin_address_line1 text,
  ADD COLUMN IF NOT EXISTS origin_address_line2 text,
  ADD COLUMN IF NOT EXISTS origin_postal_code text,
  ADD COLUMN IF NOT EXISTS origin_city text,
  ADD COLUMN IF NOT EXISTS origin_country text DEFAULT 'FRANCE',
  ADD COLUMN IF NOT EXISTS origin_floor text,
  ADD COLUMN IF NOT EXISTS origin_portage integer DEFAULT 0,
  ADD COLUMN IF NOT EXISTS origin_elevator boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS origin_furniture_lift boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS origin_transshipment boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS origin_window boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS origin_access text,
  ADD COLUMN IF NOT EXISTS origin_heavy_vehicle boolean DEFAULT false,
  -- Destination address fields
  ADD COLUMN IF NOT EXISTS dest_reference text,
  ADD COLUMN IF NOT EXISTS dest_name text,
  ADD COLUMN IF NOT EXISTS dest_address_line1 text,
  ADD COLUMN IF NOT EXISTS dest_address_line2 text,
  ADD COLUMN IF NOT EXISTS dest_postal_code text,
  ADD COLUMN IF NOT EXISTS dest_city text,
  ADD COLUMN IF NOT EXISTS dest_country text DEFAULT 'FRANCE',
  ADD COLUMN IF NOT EXISTS dest_floor text,
  ADD COLUMN IF NOT EXISTS dest_portage integer DEFAULT 0,
  ADD COLUMN IF NOT EXISTS dest_elevator boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS dest_furniture_lift boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS dest_transshipment boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS dest_window boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS dest_access text,
  ADD COLUMN IF NOT EXISTS dest_heavy_vehicle boolean DEFAULT false,
  -- Volume & logistics
  ADD COLUMN IF NOT EXISTS volume numeric DEFAULT 0,
  ADD COLUMN IF NOT EXISTS distance numeric,
  ADD COLUMN IF NOT EXISTS period text,
  -- Dossier conversion
  ADD COLUMN IF NOT EXISTS devis_type text,
  ADD COLUMN IF NOT EXISTS nature text,
  ADD COLUMN IF NOT EXISTS operation_type text,
  ADD COLUMN IF NOT EXISTS contractor text,
  ADD COLUMN IF NOT EXISTS quality integer DEFAULT 1,
  ADD COLUMN IF NOT EXISTS loading_date date;
