
-- Add dedicated columns to planning_events for all form fields
ALTER TABLE public.planning_events
  ADD COLUMN IF NOT EXISTS client_id uuid REFERENCES public.clients(id),
  ADD COLUMN IF NOT EXISTS priority text NOT NULL DEFAULT 'normale',
  ADD COLUMN IF NOT EXISTS all_day boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS internal_notes text,
  ADD COLUMN IF NOT EXISTS instructions text,
  ADD COLUMN IF NOT EXISTS volume numeric,
  ADD COLUMN IF NOT EXISTS weight numeric,
  ADD COLUMN IF NOT EXISTS loading_address text,
  ADD COLUMN IF NOT EXISTS loading_postal_code text,
  ADD COLUMN IF NOT EXISTS loading_city text,
  ADD COLUMN IF NOT EXISTS loading_floor text,
  ADD COLUMN IF NOT EXISTS loading_access text,
  ADD COLUMN IF NOT EXISTS loading_elevator boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS loading_parking_request boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS loading_portage integer DEFAULT 0,
  ADD COLUMN IF NOT EXISTS loading_passage_fenetre boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS loading_monte_meubles boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS loading_transbordement boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS loading_comments text,
  ADD COLUMN IF NOT EXISTS delivery_address text,
  ADD COLUMN IF NOT EXISTS delivery_postal_code text,
  ADD COLUMN IF NOT EXISTS delivery_city text,
  ADD COLUMN IF NOT EXISTS delivery_floor text,
  ADD COLUMN IF NOT EXISTS delivery_access text,
  ADD COLUMN IF NOT EXISTS delivery_elevator boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS delivery_parking_request boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS delivery_portage integer DEFAULT 0,
  ADD COLUMN IF NOT EXISTS delivery_passage_fenetre boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS delivery_monte_meubles boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS delivery_transbordement boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS delivery_comments text;
